[package]
name = "touch_button_panel"
version = "0.1.0"
authors = ["friedrich122112@googlemail.com <friedrich122112@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stm32f4xx-hal = { version = "0.8.3", features = ["rt", "stm32f429", "usb_fs"]}
cortex-m = "0.6.2"
cortex-m-rt = "0.6.12"
cortex-m-rtic = "0.5.3"
panic-semihosting = "0.5.3"
usb-device = "0.2.5"
usbd-hid = "0.4.4"
cortex-m-semihosting = "0.3.5"