[package]
name = "touch_button_panel"
version = "0.1.0"
authors = ["Sven Friedrich <friedrich122112@googlemail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stm32f4xx-hal = { version = "0.7.0", features = ["rt", "stm32f401", "usb_fs"] }
cortex-m = "0.6"
cortex-m-rt = { version = "0.6.10", features = ["device"] }
panic-halt = "0.2.0"
cortex-m-rtic = "0.5"
generic-array = "0.13"
embedded-hal = "0.2"
usb-device = "0.2.0"
at42qt1070 = "0.1.0"
usbd-hid = "0.4.4"
nb = "0.1.2"
usbd-hid-macros = "0.4.4"
panic-semihosting = "0.5.3"
cortex-m-semihosting = "0.3.5"